[build]
publish = "dist"          # Directory to publish (default for Vite)  
command = "npm run build" # Command to build your project  

[functions]
directory = "netlify/functions" # Specify the functions directory  

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# Handle SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200